=== lavlavlav/Provera-znanja/magacin.dtd
<!ELEMENT Magacin (Artikal)+>
<!ELEMENT Artikal (Naziv, DatumIzrade, Cena, KompanijaProdavca, EmailProdavca)>
<!ELEMENT Naziv (#PCDATA)>
<!ATTLIST Naziv tip ID #REQUIRED>

<!ELEMENT DatumIzrade (Dan, Mesec, Godina)>
<!ELEMENT Dan (#PCDATA)>
<!ELEMENT Mesec (#PCDATA)>
<!ELEMENT Godina (#PCDATA)>

<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena tip (din|eur) #REQUIRED>

<!ELEMENT KompanijaProdavca (ImeKompanije, Adresa)>
<!ELEMENT Adresa (#PCDATA)+>

<!ELEMENT EmailProdavca (#PCDATA)+>
<!ATTLIST EmailProdavca tip (privatni|sluzbeni) #REQUIRED>

=== lavlavlav/Provera-znanja/magacin.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE Magacin SYSTEM "magacin.dtd">
<Magacin xmlns="http://www.w3schools.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.w3schools.com magacin.xsd">
<Artikal>
    <Naziv sifra="2343">Cokolada</Naziv>
    <DatumIzdrade>
        <Dan>21</Dan>
        <Mesec>11</Mesec>
        <Godina>1998</Godina>
    </DatumIzdrade>
    <Cena tip="din">43434</Cena>
    <KompanijaProdavca>
        <ImeKompanije>Delhaize</ImeKompanije>
        <Adresa>Neka Nekog 32</Adresa>
    </KompanijaProdavca>
    <EmailProdavca tip="privatni">mihajilomrsevic@gmail.com</EmailProdavca>
</Artikal>
</Magacin>
